### ISSUE TITLE
ValueError: No engine for filetype: 'xls' when using ZebraZoom

### ISSUE THREAD

**Issue by ARSgang** [oliviermirat/ZebraZoom#121]
Dear Oliver,

Thank you so much for this amazing software. Recently, I am using ZebraZooom, but I got a error. I provide this error information below. Could do please tell what kind of solusions that I can utilize to solve this problem?

**I encountered an issue when trying to use ZebraZoom with an .xls file. The following error message was displayed:

Traceback (most recent call last):
  File "pandas\io\excel\_base.py", line 1136, in __new__
  File "pandas\_config\config.py", line 274, in __call__
  File "pandas\_config\config.py", line 146, in _get_option
  File "pandas\_config\config.py", line 132, in _get_single_key
pandas._config.config.OptionError: "No such keys(s): 'io.excel.xls.writer'"

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "zebrazoom\code\GUI\dataAnalysisGUI.py", line 672, in inner
  File "zebrazoom\code\GUI\dataAnalysisGUI.py", line 324, in saveFile
  File "pandas\util\_decorators.py", line 333, in wrapper
  File "pandas\core\generic.py", line 2417, in to_excel
  File "pandas\io\formats\excel.py", line 943, in write
  File "pandas\io\excel\_base.py", line 1140, in __new__
ValueError: No engine for filetype: 'xls'**

![Screenshot 2024-07-03 131014](https://github.com/oliviermirat/ZebraZoom/assets/69636072/a1a30e31-2a00-4026-8cd6-7ff5668ba08d)

Many thanks,
Trent

**Comment by oliviermirat** [comment]
Dear Trent,

Thank you for your feedback and for your interest in ZebraZoom.

We think there might be some issues with .xls files on some installations of ZebraZoom (depending on the OS and installation method used). Most likely, we will soon replace this default .xls file by a default .xlsx file.

Instead of adding a line to this file provided by default, could you please try clicking on the "New experiment" button, filling up the new file that will be created by clicking on that button (which should be a .xlsx) and then running a test analysis? Could you please let us know if that fixes the error? (there's a good chance that it will).

Best,

Olivier

**Comment by oliviermirat** [comment]
I'm closing this for now.

Please feel free to let me know if you need more help.

Best,

Olivier
