### ISSUE TITLE
Error in Analyze Zebrazoom output

### ISSUE THREAD

**Issue by Maha314** [oliviermirat/ZebraZoom#32]
Hey Olivier,

I ran into an error while trying to run a new set of tracking through the analysis pipeline. I get the following error after it calculates the parameters:

Traceback (most recent call last):
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\zebrazoom\code\GUI\dataAnalysisGUI.py", line 135, in <lambda>
launchBtn.clicked.connect(lambda: controller.populationComparison(controller, tailTrackingParametersCheckbox.isChecked(), saveInMatlabFormatCheckbox.isChecked(), saveRawDataCheckbox.isChecked(), minNbBendForBoutDetect.text(), discardRadioButton.isChecked(), keepRadioButton.isChecked(), frameStepForDistanceCalculation.text()))
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\zebrazoom\GUIAllPy.py", line 281, in populationComparison
dataAnalysisGUIFunctions.populationComparison(self, controller, TailTrackingParameters, saveInMatlabFormat, saveRawData, minNbBendForBoutDetect, discard, keep, frameStepForDistanceCalculation)
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\zebrazoom\code\GUI\dataAnalysisGUIFunctions.py", line 103, in populationComparison
[conditions, genotypes, nbFramesTakenIntoAccount, globParam] = createDataFrame(dataframeOptions, "", 0, ['BoutFrameNumberStart', 'tailAngleSymmetry', 'secondBendAmpDividedByFirst', 'tailAngleIntegral'])
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\zebrazoom\dataAnalysis\datasetcreation\createDataFrame.py", line 158, in createDataFrame
include = eval('[' + include + ']')
TypeError: can only concatenate str (not "numpy.float64") to str

thanks!

**Comment by Maha314** [comment]
It was an issue with the include column in the excel file generated. Resolved!
