### ISSUE TITLE
Error in  plotting BoutDuration using Analyse ZZ output

### ISSUE THREAD

**Issue by Maha314** [oliviermirat/ZebraZoom#34]
Hi,

I'm trying to plot  kinematic parameters using the Analyse ZZoutput option and I got the following error while plotting:

ZZ version:1.32.9

Traceback (most recent call last):
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3361, in get_loc
return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'BoutDuration'

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\zebrazoom\code\GUI\dataAnalysisGUI.py", line 135, in <lambda>
launchBtn.clicked.connect(lambda: controller.populationComparison(controller, tailTrackingParametersCheckbox.isChecked(), saveInMatlabFormatCheckbox.isChecked(), saveRawDataCheckbox.isChecked(), minNbBendForBoutDetect.text(), discardRadioButton.isChecked(), keepRadioButton.isChecked(), frameStepForDistanceCalculation.text()))
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\zebrazoom\GUIAllPy.py", line 281, in populationComparison
dataAnalysisGUIFunctions.populationComparison(self, controller, TailTrackingParameters, saveInMatlabFormat, saveRawData, minNbBendForBoutDetect, discard, keep, frameStepForDistanceCalculation)
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\zebrazoom\code\GUI\dataAnalysisGUIFunctions.py", line 115, in populationComparison
populationComparaison(nameOfFile, resFolder, globParam, conditions, genotypes, os.path.join(cur_dir_path, os.path.join('dataAnalysis', 'resultsKinematic')), 1, True)
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\zebrazoom\dataAnalysis\dataanalysis\populationComparaison.py", line 60, in populationComparaison
dfKinematicValues['percentTimeSpentSwimming'] = (dfTotalTimeMove['BoutDuration'] / dfKinematicValues['videoDuration']) * 100
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3455, in __getitem__
indexer = self.columns.get_loc(key)
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 3363, in get_loc
raise KeyError(key) from err
KeyError: 'BoutDuration'

I tried doing the same with an old version (really old, 1.30.32) and it works fine!

Probably a small bug?! Thanks!

**Comment by oliviermirat** [comment]
Hi Maha,
Thanks for the feedback. This error is related to the new 'percentTimeSpentSwimming' parameter that I recently introduced.
However, I'm not entirely sure what's causing this, I will email you about it right now.

**Comment by oliviermirat** [comment]
The error was related to the pandas version. I've changed the setup.py file to make sure that the pandas versions causing this issue don't get installed. So this bug should now be resolved in the latest ZebraZoom version (1.32.11).
