### ISSUE TITLE
error in opening version of 1.32.37 zebrazoom 

### ISSUE THREAD

**Issue by Maha314** [oliviermirat/ZebraZoom#56]
Hi Olivier,

I updated the version of ZZ and tried to open it I got the following error:
Not sure what is wrong:

Traceback (most recent call last):
  File "C:\Users\m.dhanasekar\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
  File "C:\Users\m.dhanasekar\Anaconda3\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\zebrazoom\__main__.py", line 14, in <module>
app = ZebraZoomApp(sys.argv)
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\zebrazoom\GUIAllPy.py", line 117, in __init__
page = F(self)
  File "C:\Users\m.dhanasekar\Anaconda3\lib\site-packages\zebrazoom\code\GUI\GUI_InitialClasses.py", line 31, in __init__
super().__init__(controller.window)
TypeError: QWidget(parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.WindowFlags()): argument 1 has unexpected type 'QMainWindow'

Lemme know if you need more information!

**Comment by oliviermirat** [comment]
Thank you for the feedback @Maha314
@anthepro can you please take a look?

**Comment by oliviermirat** [comment]
@Maha314 : can you please update to the latest version (1.32.38) and tell us if it's working now (it should)

**Comment by Maha314** [comment]
Works now! Thanks :)
