### ISSUE TITLE
AttributeError: 'list' object object has no attribute 'shape' when creating a new config file for .seq video

### ISSUE THREAD

**Issue by Cilia-Jia** [oliviermirat/ZebraZoom#83]
Hi,

 I am using .seq file for tracking. I am getting AttributeError: 'list' object object has no attribute 'shape' that prevented me from starting the process of creating a new config file for this video. An unfinished config file is saved.

Traceback (most recent call last):
  File "zebrazoom\code\GUI\configFilePrepare.py", line 608, in mousePressEvent
  File "zebrazoom\code\GUI\configFilePrepare.py", line 645, in <lambda>
  File "zebrazoom\GUIAllPy.py", line 246, in chooseGeneralExperimentFirstStep
  File "zebrazoom\code\util.py", line 1122, in inner
  File "zebrazoom\code\GUI\configFilePrepareFunctions.py", line 67, in chooseGeneralExperimentFirstStep
  File "zebrazoom\code\GUI\configFilePrepareFunctions.py", line 83, in chooseGeneralExperiment
  File "zebrazoom\code\GUI\configFilePrepareFunctions.py", line 273, in chooseBeginningAndEndOfVideo
  File "zebrazoom\code\util.py", line 674, in chooseBeginningPage
  File "zebrazoom\code\util.py", line 423, in setPixmapFromCv
  File "zebrazoom\code\util.py", line 230, in _cvToPixmap
AttributeError: 'list' object has no attribute 'shape'

**Comment by oliviermirat** [comment]
Hi,
I would need to see the video to figure out what's happening. But it looks like there might be something strange with the video (maybe some missing .bin files for example). Please check if anything looks strange with the video and if everything looks fine with it please send me the video and I will investigate.

**Comment by oliviermirat** [comment]
I'm closing this issue for now but I would be happy to reopen it later if necessary: please just reopen it and/or contact me if it's necessary.

**Comment by oliviermirat** [comment]
I'm closing this issue for now but I would be happy to reopen it later if necessary: please just reopen it and/or contact me if it's necessary.
