### ISSUE TITLE
Error while visualizing tracking results from files ran using the cluster

### ISSUE THREAD

**Issue by Maha314** [oliviermirat/ZebraZoom#84]
Hey Olivier,

I'm getting the following error while visualizing tracking results of some files launched using cluster:
Version of ZZ used: 1.33.13

Traceback (most recent call last):
  File "C:\Users\m.dhanasekar\AppData\Local\conda\conda\envs\zebrazoom\lib\site-packages\zebrazoom\code\GUI\GUI_InitialClasses.py", line 639, in <lambda>
selectionModel.currentRowChanged.connect(lambda current, previous: current.row() == -1 or self.setFolder(model.fileName(current)))
  File "C:\Users\m.dhanasekar\AppData\Local\conda\conda\envs\zebrazoom\lib\site-packages\zebrazoom\code\GUI\GUI_InitialClasses.py", line 822, in setFolder
self.dataRef = json.load(ff)
  File "C:\Users\m.dhanasekar\AppData\Local\conda\conda\envs\zebrazoom\lib\json\__init__.py", line 293, in load
return loads(fp.read(),
  File "C:\Users\m.dhanasekar\AppData\Local\conda\conda\envs\zebrazoom\lib\json\__init__.py", line 357, in loads
return _default_decoder.decode(s)
  File "C:\Users\m.dhanasekar\AppData\Local\conda\conda\envs\zebrazoom\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\m.dhanasekar\AppData\Local\conda\conda\envs\zebrazoom\lib\json\decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 16605161 (char 16605160)

Also, FYI: when you visualize results from files ran on the cluster, I need to input the path of the video for every file in the GUI to be able to look at the videos of the bouts.

**Comment by oliviermirat** [comment]
I'm closing this issue for now but I would be happy to reopen it later if necessary: please just reopen it and/or contact me if it's necessary.
