### ISSUE TITLE
Running Fails with numpy 1.24

### ISSUE THREAD

**Issue by CorbanSwain** [oliviermirat/ZebraZoom#85]
It seems that there is a small incompatibility with zebrazoom 1.33.13 and numpy 1.24.

## Steps to recreate the issue (as of 2023.02.28) on Windows with miniforge:
1. Open Anaconda prompt.
1. Create new python 3.8 enviornment:
   ```
   conda create --prefix .\zebrazoom-env-3.8 python=3.8
   ```
1. Activate enviornment:
   ```
   conda activate .\zebrazoom-env-3.8
   ```
1. Install zebrazoom:
   ```
   pip install zebrazoom
   ```
   *Note that this step installs `zebrazoom-1.33.13` and  `numpy-1.24.2` as a dependency.*
1. Run zebrazoom:
   ```
   python -m zebrazoom
   ```
   This fails with the following error:
    ```
    Traceback (most recent call last):
      File "I:\CorbanSwain\repos\zmia\envs\zebrazoom-env-3.8\lib\runpy.py", line 185, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "I:\CorbanSwain\repos\zmia\envs\zebrazoom-env-3.8\lib\runpy.py", line 144, in _get_module_details
        return _get_module_details(pkg_main_name, error)
      File "I:\CorbanSwain\repos\zmia\envs\zebrazoom-env-3.8\lib\runpy.py", line 111, in _get_module_details
        __import__(pkg_name)
      File "I:\CorbanSwain\repos\zmia\envs\zebrazoom-env-3.8\lib\site-packages\zebrazoom\__init__.py", line 4, in <module>
        from zebrazoom.dataAnalysis.datasetcreation.createDataFrame import createDataFrame
      File "I:\CorbanSwain\repos\zmia\envs\zebrazoom-env-3.8\lib\site-packages\zebrazoom\dataAnalysis\datasetcreation\createDataFrame.py", line 7, in <module>
        np.warnings.filterwarnings('ignore', category=np.VisibleDeprecationWarning)
      File "I:\CorbanSwain\repos\zmia\envs\zebrazoom-env-3.8\lib\site-packages\numpy\__init__.py", line 320, in __getattr__
        raise AttributeError("module {!r} has no attribute "
    AttributeError: module 'numpy' has no attribute 'warnings'
    ```

## Quick Fix for this issue
Steps continued from above
1. Downgrade numpy:
   ```
   conda insttall numpy=1.23
   ```
1. Run zebrazoom:
   ```
   python -m zebrazoom
   ```

**Comment by CorbanSwain** [comment]
This seems to be the problem line in the source code
https://github.com/oliviermirat/ZebraZoom/blob/e8a9ba6eb564cedc74e06c57a01141ef5201124e/zebrazoom/dataAnalysis/datasetcreation/createDataFrame.py#L7

**Comment by CorbanSwain** [comment]
It seems that the call to `np.warnings` is simply accessing the builtin python `warnings` module via the `numpy.__init__` file's namespace. So the problem line should be able to be replaced with:
```python
import warnings
warnings.filterwarnings(...)
```

**Comment by oliviermirat** [comment]
Hi Corban,
Thank you so much for reporting this issue and for submitting a pull request!
The fix you proposed seems to work so I accepted your pull request.
Thanks again!
Olivier
