### ISSUE TITLE
Kinematic parameters analysis problem with anaconda version with the default "example"

### ISSUE THREAD

**Issue by oliviermirat** [oliviermirat/ZebraZoom#89]

**Comment by oliviermirat** [comment]
![image](https://user-images.githubusercontent.com/17452771/224889764-bd6e76e0-24f3-46b0-b207-f1baf68256d3.png)

**Comment by oliviermirat** [comment]
(base) C:\Users\mirat\Downloads\ZebraZoom-master\ZebraZoom-master>python -m zebrazoom
The data produced by ZebraZoom can be found in the folder: C:\Users\mirat\Downloads\ZebraZoom-master\ZebraZoom-master\zebrazoom\ZZoutput
Generating pkl datafile for video example1 , because:
the path C:\Users\mirat\Downloads\ZebraZoom-master\ZebraZoom-master\zebrazoom\ZZoutput\example1\example1.pkl does not exist
len(parametersUsedForCalculation) is equal to 0
Creating pandas dataframe of parameters
Parameter: frameStepForDistanceCalculation: 4
Calculating and storing all parameters:
frameStepForDistanceCalculation 4
videoFPS 160.0
videoPixelSize 70.0
trial_id: example1  ; Well_ID: 0
Traceback (most recent call last):
  File "C:\Users\mirat\Downloads\ZebraZoom-master\ZebraZoom-master\zebrazoom\code\GUI\dataAnalysisGUI.py", line 1051, in <lambda>
    self._launchBtn.clicked.connect(lambda: self._populationComparison(self._tailTrackingParametersCheckbox.isChecked(), self._saveInMatlabFormatCheckbox.isChecked(), self._saveRawDataCheckbox.isChecked(), self._forcePandasRecreation.isChecked(), '0' if self._noOutlierRemovalButton.isChecked() else self._minNbBendForBoutDetect.text() if self._bendsOutlierRemovalButton.isChecked() else None, self._keepDiscardedBoutsCheckbox.isChecked(), self._frameStepForDistanceCalculation.text()))
  File "C:\Users\mirat\Downloads\ZebraZoom-master\ZebraZoom-master\zebrazoom\code\util.py", line 173, in inner
    retval = fn(*args, **kwargs)  # XXX: GUI and non-GUI parts are still mixed so this function is expected to set the new page
  File "C:\Users\mirat\Downloads\ZebraZoom-master\ZebraZoom-master\zebrazoom\code\GUI\dataAnalysisGUI.py", line 1098, in _populationComparison
    generatePklDataFileForVideo(os.path.join(self.controller.experimentOrganizationExcelFileAndFolder, self.controller.experimentOrganizationExcel), ZZoutputLocation, frameStepForDistanceCalculation, forcePandasRecreation)
  File "C:\Users\mirat\Downloads\ZebraZoom-master\ZebraZoom-master\zebrazoom\dataAnalysis\datasetcreation\generatePklDataFileForVideo.py", line 42, in generatePklDataFileForVideo
    createPandasDataFrameOfParameters(hyperparameters, videoName, videoExtension, ZZoutputLocation if excelFile.loc[videoId, 'path'] == "defaultZZoutputFolder" else excelFile.loc[videoId, 'path'])
  File "C:\Users\mirat\Downloads\ZebraZoom-master\ZebraZoom-master\zebrazoom\code\dataPostProcessing\createPandasDataFrameOfParameters.py", line 47, in createPandasDataFrameOfParameters
    [conditions, genotypes, nbFramesTakenIntoAccount, globParam] = createDataFrame(dataframeOptions, excelFileDataFrame, 1, [], 0, supstructOverwrite)
  File "C:\Users\mirat\Downloads\ZebraZoom-master\ZebraZoom-master\zebrazoom\dataAnalysis\datasetcreation\createDataFrame.py", line 297, in createDataFrame
    dfParamForWell.loc[curBoutId, toPutInDataFrameColumn] = toPutInDataFrame
  File "C:\Users\mirat\anaconda3\lib\site-packages\pandas\core\indexing.py", line 716, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "C:\Users\mirat\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1690, in _setitem_with_indexer
    self._setitem_single_block(indexer, value, name)
  File "C:\Users\mirat\anaconda3\lib\site-packages\pandas\core\indexing.py", line 1938, in _setitem_single_block
    self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
  File "C:\Users\mirat\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 337, in setitem
    return self.apply("setitem", indexer=indexer, value=value)
  File "C:\Users\mirat\anaconda3\lib\site-packages\pandas\core\internals\managers.py", line 304, in apply
    applied = getattr(b, f)(**kwargs)
  File "C:\Users\mirat\anaconda3\lib\site-packages\pandas\core\internals\blocks.py", line 924, in setitem
    arr_value = np.asarray(value)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (747,) + inhomogeneous part.
